In [7]:
import numpy as np
import scipy.sparse

In [3]:
a = np.array([[13.122362232756892, 12.908730797787177, 12.969074246807999, 1., ],
[12.908730797787177, 13.395137277140243, 12.686909980461042, 1., ],
[12.969074246807999, 12.686909980461042, 13.4993286861243, 1., ],
[1., 1., 1., 0., ]])

In [4]:
a

array([[13.12236223, 12.9087308 , 12.96907425,  1.        ],
       [12.9087308 , 13.39513728, 12.68690998,  1.        ],
       [12.96907425, 12.68690998, 13.49932869,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  0.        ]])

In [5]:
b = np.array([-0.0887084812224098, 0.066417522785488, 0.0630470978361748, 0., ])
b

array([-0.08870848,  0.06641752,  0.0630471 ,  0.        ])

In [8]:
A = scipy.sparse.csr_matrix(a)

In [9]:
A.shape

(4, 4)

In [11]:
import scipy.sparse.linalg

In [13]:
scipy.sparse.linalg.spsolve(A, b)

array([-0.49239545,  0.24574349,  0.24665196,  0.00159883])